name:  my first workflow
on: push
jobs:
  test_job:
    runs-on: ubuntu-latest
    steps:
      - name:  Pull the code
        uses: actions/checkout@v3
      - name:  install dependencies
        run: pip install -r requirements.txt
      - name:  run flask db commands
        run: |
            flask db init
            flask db migrate
            flask db upgrade  